Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "srv-pix"    
    # Sincronizar o diretório da aplicação
    config.vm.synced_folder "./app", "/srv-pix/app"
    
    # Provisionamento automático
    config.vm.provision "shell", path: "provision/setup.sh"
  end
  